// react/react-core/src/components/ActionButtonList.tsx
import { useDisconnect, useAppKit, useAppKitNetwork, useAppKitAccount, useAppKitProvider, type Provider } from '@reown/appkit/react'
import { networks } from '../config'


export const ActionButtonList = () => {
    const { disconnect } = useDisconnect(); // AppKit hook to disconnect
    const { open } = useAppKit(); // AppKit hook to open the modal
    const { switchNetwork } = useAppKitNetwork(); // AppKithook to switch network
    const { address, isConnected } = useAppKitAccount() // AppKit hook to get the address and check if the user is connected
    const { walletProvider } = useAppKitProvider<Provider>('eip155')


    const handleDisconnect = async () => {
      try {
        await disconnect();
      } catch (error) {
        console.error("Failed to disconnect:", error);
      }
    };

    // function to sing a msg 
    const handleSignMsg = async () => {
      const message = "Hello Reown AppKit!" // message to sign
      try {
        const result = await walletProvider.request({
          method: 'personal_sign',
          params: [message, address]
        }) as { signature: string }
        
        console.log("result", result);
      } catch (error: any) {
        console.log("error", error);
        throw new Error(error);
      }
    }

  return (
    isConnected && (
    <div >
        <button onClick={() => open()}>Open</button>
        <button onClick={handleDisconnect}>Disconnect</button>
        <button onClick={() => switchNetwork(networks[1]) }>Switch</button>
        <button onClick={handleSignMsg}>Sign</button>
    </div>
    )
  )
}

// svelte/svelte-tron/src/lib/ActionButtonList.svelte
<script>
  import { appKit, networks } from '../config/appKit'
  import { account, tronProvider } from './store'

  let signature = $state('')
  let balance = $state('')

  const isConnected = $derived($account?.isConnected ?? false)

  async function handleDisconnect() {
    try {
      await appKit.disconnect()
      signature = ''
      balance = ''
    } catch (error) {
      console.error('Failed to disconnect:', error)
    }
  }

  async function handleSignMessage() {
    const provider = $tronProvider
    const address = $account?.address
    if (!provider || !address) return
    try {
      signature = await provider.signMessage({
        message: 'Hello from AppKit Tron example!',
        from: address
      })
    } catch (error) {
      console.error('Failed to sign message:', error)
    }
  }

  async function handleGetBalance() {
    try {
      // The `fetchBalance` helper is React/Vue-only, so we call the public
      // base-client methods it wraps directly.
      const address = appKit.getAddress()
      const namespace = appKit.getActiveChainNamespace()
      const chainId = appKit.getCaipNetwork()?.id
      if (!address || !namespace || !chainId) {
        console.error('Not able to retrieve balance')
        return
      }
      const result = await appKit.updateNativeBalance(address, chainId, namespace)
      if (result) {
        balance = `${result.balance} ${result.symbol}`
      } else {
        console.error('No balance found')
      }
    } catch (error) {
      console.error('Failed to fetch balance:', error)
    }
  }
</script>

<div>
  <button onclick={() => appKit.open()}>Open</button>
  <button onclick={handleDisconnect}>Disconnect</button>
  <button onclick={() => appKit.switchNetwork(networks[1])}>Switch</button>
  <button onclick={handleSignMessage} disabled={!isConnected}>Sign Message</button>
  <button onclick={handleGetBalance} disabled={!isConnected}>Get Balance</button>
</div>

{#if signature || balance}
  <section>
    <h2>Actions</h2>
    <pre>{#if balance}Balance: {balance}
{/if}{#if signature}Signature: {signature}{/if}</pre>
  </section>
{/if}
