// vue/vue-multichain/src/App.vue

<template>
   <div class="pages">
      <img src="/reown.svg" alt="Reown" width="150" height="150" />
      <h1>AppKit multichain vue Example</h1>

      <appkit-button />
      <ActionButtonList />
      <div className="advice">
        <p>
          This projectId only works on localhost. <br/>
          Go to <a href="https://dashboard.reown.com" target="_blank" className="link-button" rel="Reown Dashboard">Reown Dashboard</a> to get your own.
        </p>
      </div>
      <InfoList />
    </div>
</template>


<script>
import ActionButtonList from "./components/ActionButton.vue";
import InfoList from "./components/InfoList.vue";
import './config/index' // Ensure AppKit is initialized

export default {
  name: "App",
  components: {
    ActionButtonList,
    InfoList
  },
};
</script>

// nextjs/next-siwx-multichain/src/app/page.tsx
import { ConnectButton } from "@/components/ConnectButton";
import { InfoList } from "@/components/InfoList";
import { ActionButtonList } from "@/components/ActionButtonList";
import Image from "next/image";

export default function Home() {
  return (
    <div className={"pages"}>
      <Image src="/reown.svg" alt="Reown" width={150} height={150} priority />
      <h1>AppKit Multichain SIWX - App Router Example</h1>

      <ConnectButton />
      <ActionButtonList />
      <div className="advice">
        <p>
          This projectId only works on localhost. <br />
          Go to{" "}
          <a
            href="https://dashboard.reown.com"
            target="_blank"
            className="link-button"
            rel="Reown Dashboard"
          >
            Reown Dashboard
          </a>{" "}
          to get your own.
        </p>
      </div>
      <InfoList />
    </div>
  );
}
